# Introduction
*Because the hook brings you back
I ain't tellin' you no lie
The hook brings you back
On that you can rely*

*Hook Möglichkeit 1:
Renate Künast: Opfer von Hate Speech wegen Falschdarstellung ihrer ursprünglichen Aussage. Zeigt das Hand-in-Hand-Gehen von Hate Speech und Disinformation und die Schwierigkeiten, die wir als Gesellschaft haben, damit umzugehen (unterschiedliche Gerichtsentscheidungen, viele kritisieren Begründungen des Gerichts). Problem: Kontrovers, inwieweit ist eine leichte Umformulierung ihrer ursprünglichen Aussage Disinformation
https://www.zdf.de/nachrichten/politik/renate-kuenast-erzielt-teilerfolg-100.html*

*Hook Möglichkeit 2:
Facebook lässt (in den USA) weiter Lügen in politischer Werbung zu. Stellt in Frage, ob wir uns im Kampf gegen Hate Speech und Disinformation auf Institutionen verlassen können. Historischer RÜckbezug zu Trumps alten hateful Anzeigen bringt Bezug zu Hate Speech. 
https://www.nytimes.com/2020/01/09/technology/facebook-political-ads-lies.html*

Arguably, hate speech and disinformation are overlapping phenomena, both highly influential and both linked to increasing political polarization. One possible strategy in challenging hate speech is counter speech. But who are the counter speakers and what motivates them to fight hate speech and disinformation? And how can counter speech influence polarization?

We will start out this paper by describing the connection between hate speech and disinformation as well as their detrimental effects. Afterwards, we will collect existing research on counter speech, both its effects as well as what motivates users to counter speak. We will then present the results from our on research where we asked both active counter speakers as well as more passive users about their motivation to (not) engage in counter speech. Finally, we will discuss the implications of our findings.