# Results
As figure \@ref(fig:categorization)) shows, we contrasted the results of both groups for each category, (_description_, _conditions_ and _motivations_). As our research question focusses on predictors, only a quick overview will be given for the category _description_.

For the sake of brevity, in the following sections these terms will be used:
_Hater:_ The perpetrator of the hate speech,
_victim(s):_ the recipient(s) or subject(s) of the hate speech, and
_adversary victim(s):_ victim(s) or subject(s) of hate speech that represent a group the participant politically or personally opposes.

## Description: Experiences with hate speech and handling hate speech
When describing their experiences with hate speech, both groups mention similar attributes of hate speech (e.g., the online _spaces_ where they have most often observed it). However, while four of the six very active participants report to have themselves been victims of hate speech, only one moderately active participants does so as well. There are also notable differences in the way participants of both groups handle hate speech: While participants in the moderately active group tend to look at hateful comments only for entertainment value or avoid looking at comments at all, many participants in the very active groupactively seek out hate speech comments in order to fight it.

## Conditions: When to engage in counter speech
For a given situation, participants describe both conditions that make it more likely that they engage in counter speech ( _positive conditions_) as well as conditions that make it less likely ( _negative conditions_). As mentioned above, the participants in the moderately active group reported to only seldomely engage in counter speech at all, much less counter speech favoring _adversary victims_, i.e., politically opposed users that are targetted by hate speech. Therefore, most of the conditions listed are to be understood as conditions for counter speech in general. The only exception is the subcategory _positive conditions_ for the very active group where a differentiation between counter speech in general and counter speech favoring _adversary victims_ was possible.






### Positive conditions for counter speech favoring adversaries.
When it comes defending people who they are politically opposed to, the following conditions emerged in the very active group: **1) Offenses against a "culture of discussion"**, i.e., the participant feels that the hater breaks the rules for a respectful debate, **2) offenses against the human dignity**, i.e., the participant feels that the hater debases the victim's human dignity, **3) properties of the victim**, e.g., the participants feels sympathy for the victim, and
 **4) a personal connection to the topic discussed**.

### Positive conditions for counter speech in general.
#### Properties of the hate speech.
Concerning the properties of the hate speech or the situation where the hate speech occurs, participants of both groups mention they are more likely to step in when they feel that their _counter speech is likely to have an impact_, e.g., there are not that many comments overall.
Additionally, participants of the very active group name the space as an important factor. They are more likely to step in when there is hate speech **1) outside of hater-dominated spaces**, e.g., not in a dedicated facebook group, or
**2) in a more private space**, e.g., in a personal chat group.

On the other side, participants of the moderately active group mention **3) calls to violence and threats** as well as
**4) doxxing**, i.e., finding and disseminating the victim's personal information,
as factors making counter speech more likely for them.

#### Properties of the victim.
Relating to the properties of the victim, both groups mention that they would be more likely to intervene if
**1) the victim is a private citizen_** or if **2) they know the victim personally**, although that is more important in the moderately active group.
Additionaly, particicpants of the very active group would be more likely to engage in counter speech if **3) the victim is an activist**.

#### Personal attributes.
Participants of both group state that they are more likely to step in if they are **1) well informed about the topic of discussion**. Members of the very active group also name **2) free time and mental energy** as a condition. Some members of the moderately active group, on the other hand, describe **3) feeling frustrated and angry** or **4) having a personal connection** to the topic of discussion as a conductor for counter~speech.


### Negative conditions for counter speech in general.
Many of the _negative conditions_ mentioned in the group are merely negations of the _positive conditions_ already listed and will therefore not be reported again.

####  Properties of the hate speech.
Members of both group state that they are less likely to engage in counter speech, when **1) both sides of the discussion engage in hate speech** or when
**2) the hate/ speech is entertaining to them**.

Additionally, participants of the very active group are less willing to intervene when they fear **3) personal risk to themselves**.

#### Properties of the victim
Apart from the negatives to the _positive conditions_ already mentioned, one member of the very active group reports that they would be less likely to intervene if they suspect _the victim is eager to be seen as a victim by the public_.

## Motivations: Why to engage in counter/ speech
Just as with the conditions, the _motivations_ of the participants could also be categorized into _motivations for intervention_ and _motivations against intervention_. In this context, _motivations_ relate to the participants' attitudes towards counter/ speech in general. By contrast, the _conditions_ listed above relate to specific situations.

### Motivations for intervention
The _motivations for intervention_ can be further categorized into _goals and values_ and _personal attributes and experiences_.

#### Goals and values
Participants of both groups concede that while they might not be able to dissuade the hater from their destructive behavior, they still _hope to positively influence the audience_.
Members of the very active group are additionally motivated by the desire to

* _fight disinformation_,
* _motivate critical thinking in other users_,
* _create a better culture of discussion in online spaces_ and
* _engage politically_.

Moderately active participants, on the other hand, worry that _online hate might spark offline violence_.

#### Personal attributes and experiences
When it comes to their personal attributes and experiences that motivate them to engage in counter/ speech, participants of both groups mention

* _a strong sense of justice_ and
* _a sense of responsibility_.

In addition, very active participants name

* _enjoying debating_,
* _own experiences with bullying and discrimination_, 
* _enjoying self-promotion_, as well as
* _being thanked and admired by others_, e.g. by site administrators,

as motivators.

### Motivations against intervention
Members of both groups name one main motivation not to engage in counter/ speech: They think it is _not worth the effort_. On top of that, members of the very active group mainly mention _fatigue_ with fighting hate/ speech in general as something that demotivates them from engaging in counter/ speech.

Among the moderately active participants, a considerable number more motivations are named:

* _A general unwillingness to participate in online communication_,
* _a preference for alternative approaches to hate/ speech_, e.g. blocking the perpetrator or even reporting them to the police,
* _the chance to be successful is perceived as too small_ and
* _their own tendency to avoid reading comments at all_.