# Discussion and Conclusion
Notably, a vast difference in engagement levels between the participants was found. While some would not engage in online discourse at all and consequently would not engage in counter speech either, others were hyperactive on social media, placing a lot of value on political discourse in online spaces. Participants in the latter group reported a much higher likelihood to engage in counter speech, be it on behalf of opponents or in general.

Overall, the relationship between the counter speaker and the victim which we focussed on in our research question (*In social media discussions, what motivates users to engage in counter speech in support of political adversaries?*) seems to be less important than the willingness to engage in counter speech in general. While we collected and categorized the predictors for counter speech reported by our participants in _conditions_, i.e., situational predictors, and _motivations_, i.e., general predictors, there is only a small number of predictors from the subset _conditions_ strictly in answer to our research question:

Three basic motivations for users to engage in counter speech in support of political adversaries can be differentiated: 
Firstly, the hater violates norms or values that are more important to the counter speaker than political affiliation. 
Values named here were a "culture of discussion", i.e., an implicit set of rules for a respectful debate, and "human dignity". 
These conditions tie somewhat into other findings about counter speakers placing high importance on morality [@lambeStandingBullyingSocial2019; @wilhelmGenderedMoralityBacklash2019]. 
Interestingly, they also mirror the vision of the internet as a place for public deliberation [@chenOnlineIncivilityPublic2017].
Productive debates can only happen if all participants follow the rules, no matter which side they are on. 
Secondly, counter speech is more likely if the participants feels sympathetic towards the victim. 
This is similar to results from cyber-bullying research [@lambeStandingBullyingSocial2019]. Thirdly, participants are more likely to intervene when they feel a personal connection to the topic of discussion. Both the second and the third motivation are limited in their generalizability. Sympathies are likely to wane the larger the distance on the political spectrum gets. 
And in many occurences of hate speech, there will be no connection to a tangible discussion topic.

The other predictors we found refer to counter speech in general and therefore do not strictly answer the research question. However, as posited above, we did not observe the expected divide between people engaging in counter speech only for friends or members of their in-group and people engaging in counter speech for everyone---including adversaries. Rather, the divide was between people engaging in counter speech for everyone, regardless of political or group affiliation, and people not generally engaging in counter speech. As such, we feel that the _motivations_ of the very active group questioned also partly answer the question of what motivates counter speakers. 

The most important _motivations_ we found were deep-seated moral convictions and a feeling of responsibility to uphold those convictions. This does not only match the findings by on the importance of morality by @wilhelmGenderedMoralityBacklash2019 and @lambeStandingBullyingSocial2019. The acceptance of responsibility also matches the bystander model of intervention often used to describe bystander behavior in cyber-bullying incidents (e.g., [@naabFlaggingUncivilUser2018]). 
Moreover, the participants felt that online discourse is an important part of political participation [@chenOnlineIncivilityPublic2017]. 
Many of the active counter speakers we talked to saw their actions as a form of activism. One of their major goals was not to change the behavior of the people engaging in hate speech, but to positively influence the broader audience. This matches what @buergerCounterspeechLiteratureReview2019 calls the contagion effect.

In conclusion, when looking at what motivates a person to regularly engage in counter speech, their relationship to the victim appears to be secondary. Of greater importance seems to be what part morality plays in that person's self-image and how willing they are to accept and defend online spaces as a place for public deliberation. 

Finally, some limitations have to be noted: Firstly, although we tried to emphasize the relationship aspect (i.e., counter speech _in favor of adversaries_) in our research design, stressing this emphasis during the focus groups proved challenging. Rather, participants tended to talk about their experiences with counter speech _in general_. This holds especially true for the participants of the moderately active group, many of whom never had engaged in counter speech at all. Therefore, our results are not suitable to evaluate whether there are differences between predictors for counter speech _in favor of adversaries_ and counter speech _in general_. Secondly, our sample was comparatively young, highly educated and politically left-aligned. It is entirely possible that other predictors not mentioned here are important with counter speakers who are, e.g., more politically right-leaning. In any case, 