---
title: "Defend Your Enemy. A Qualitative Study on Defending Political Opponents Against Hate Speech Online"
title-running: "Defend Your Enemy Against Hate Speech" 
author-inputfile: "authors.tex" 
abstract: |
  Both hate speech and disinformation negatively influence the internet's potential for public deliberation and lead to polarization between political groups. In this paper, we examine the potential of counter speech to bolster public deliberation and reduce polarization. In two focus groups, we interview participants on what motivates them to engage in counter speech in general as well as counter speech favoring political adversaries. Firstly, we find a sharp distinction between participants who avoid engaging with hate speech and participants who actively engage with hate speech in order to combat it. Thus, the most important predictor for counter speech favoring adversaries is an individual's propensity for counter speech in general. In turn, motivations for counter speech in general are a strong sense of morality, a perception of the internet as an important space for public deliberation, and a sense of responsibility to enforce rules for a fair debate. Many of those participants view their online activitiy as a form of activism. Additionally, individuals engaging in counter speech hope to positively influence not necessarily the hater, but the broader audience.
keywords: "Hate Speech \\and Counter Speech \\and Social Media \\and Political Deliberation"
bibliography: ["rpackages.bib", "bibliography.bib"]
biblio-style: "apalike"
link-citations: true
output:
  bookdown::pdf_document2:
    fig_caption: true
    keep_tex: false
    template: lncs-template.tex
    md_extensions: +footnotes
    citation_package: biblatex
    dev: pdf
---


```{r setup, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, paged.print=TRUE}
## Global options
library(knitr)
#options(max.print="75")
opts_chunk$set(echo = FALSE,
	             cache = FALSE,
               prompt = FALSE,
               tidy = TRUE,
               comment = NA,
               message = FALSE,
               warning = FALSE,
               out.width = '100%'
               )
opts_knit$set(width = 100)

# Load required libraries
library(rmdformats)
library(rmdtemplates)
library(tidyverse)
library(cowplot)
library(citr)
library(kableExtra)
# add libraries here

# Add libraries to cite here:
pkgs <- c("knitr", "tidyverse", "rmdformats", "kableExtra", "rmdtemplates", "citr")
rmdtemplates::write_bib(pkgs)
```

\Urlmuskip=0mu plus 1mu
\setcounter{footnote}{0}

```{r introduction, eval=FALSE, child='10-introduction', include=FALSE}
```
```{r related-work, child='20_related-work.Rmd'}
```
```{r method, echo=FALSE, child='30_method.Rmd'}
```
```{r results, child='40_Results.Rmd', eval = TRUE}
```
```{r discussion-and-conclusion, child='50_discussion-and-conclusion.Rmd'}
```

```{r dummy, child = '99_dummy.Rmd', eval = FALSE}
```

```{r acks, echo=FALSE, child='90_acks.Rmd'}
```

# References
